# Generated by Django 5.0.6 on 2024-12-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_brand_vid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='vid',
            new_name='bid',
        ),
    ]
