# Generated by Django 5.0.6 on 2024-12-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_productimages_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
