# Generated by Django 5.0.6 on 2024-11-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentications', '0002_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
